### ISSUE TITLE
Using the API on Odoo 11 returns ERROR

### ISSUE THREAD

**Issue by bwilmus** [DeBortoliWines/openerp-java-api#44]
Hi,

I try to connect on a Odoo 11 using the API with the following method:
			openERPSession = new Session(url, 8069, db, user, pass);
			openERPSession.startSession();
The error message is: HTTP server returned unexpected status: INTERNAL SERVER ERROR
When I look at the log file on the Odoo server, I see the following error:

2017-11-21 08:38:34,357 32119 INFO ? werkzeug: 87.90.27.99 - - [21/Nov/2017 08:38:34] "POST /xmlrpc/2/common HTTP/1.1" 500 -
2017-11-21 08:38:34,358 32119 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 251, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 122, in wsgi_xmlrpc
    params, method = xmlrpclib.loads(data)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 999, in loads
    p.feed(data)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 438, in feed
    self._parser.Parse(data, 0)
  File "../Modules/pyexpat.c", line 414, in StartElement

  File "/usr/lib/python3.5/xmlrpc/client.py", line 674, in start
    raise ResponseError("unknown tag %r" % tag)
xmlrpc.client.ResponseError: ResponseError("unknown tag 'ex:nil'",)

Can someone help me on this?

Regards,

Bernard

**Comment by flotho** [comment]
Hi, could you display before connexion the values for url, db, user and pass ?

**Comment by bwilmus** [comment]
Thanks flotho,

I don't know why but 2 of those parameters where null.
I deleted them all, save, recreate and 2 others where null too.
It looks like a pentaho problem, not linked to the API.

Thanks again
