### ISSUE TITLE
Error Response 

### ISSUE THREAD

**Issue by levkar** [DeBortoliWines/openerp-java-api#51]
Odoo returns all error messages but library fails to show them properly.

### Error Message:

Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.util.Map;
	at com.debortoliwines.odoo.api.ObjectAdapter.importDataV7(ObjectAdapter.java:635)
	at com.debortoliwines.odoo.api.ObjectAdapter.importData(ObjectAdapter.java:584)

### Fails at this line:

https://github.com/DeBortoliWines/openerp-java-api/blob/eb023faa5c9d322b9c75980bd1803ecde8b7595a/src/main/java/com/odoojava/api/ObjectAdapter.java#L673

**Comment by flotho** [comment]
Hi @levkar ,

could you precise the way you call the methods.
Which version of Odoo do you running, more info would be appreciated.
regards
