### ISSUE TITLE
get Bad Request white trying to getObjectAdapter

### ISSUE THREAD

**Issue by siddharthkrish** [DeBortoliWines/openerp-java-api#8]
port that i'm trying to connect to is 443 (https).
org.apache.xmlrpc.client.XmlRpcHttpTransportException: HTTP server returned unexpected status: Bad Request
    at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:94)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
    at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
    at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
    at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
    at com.debortoliwines.openerp.api.OpenERPXmlRpcProxy.getServerVersion(OpenERPXmlRpcProxy.java:177)
    at com.debortoliwines.openerp.api.OpenERPXmlRpcProxy.getServerVersion(OpenERPXmlRpcProxy.java:162)
    at com.debortoliwines.openerp.api.Session.getServerVersion(Session.java:222)
    at com.debortoliwines.openerp.api.ObjectAdapter.<init>(ObjectAdapter.java:65)
    at com.debortoliwines.openerp.api.Session.getObjectAdapter(Session.java:92)
    at controllers.OpenERP.create(OpenERP.java:50)

**Comment by flotho** [comment]
Hy,

It seems that you didn't succeed in connecting to the server. 
What instance are your trying to reach? The odoo saas one or a self hosted one?
If it's your own library you'll probably able to make local tests with IP:port instead an https://domain.tld which would probably will be reverse proxied.

Thanks in advance for your precisions

**Comment by flotho** [comment]
Hi @siddharthkrish ,

Working with https seems to be needing some additionnal R&D. Both the server part and the client are probably part of the clue.
I'll let you know when I'll make additionnal tests

regards

**Comment by flotho** [comment]
Thanks @challs,
